### ISSUE TITLE
 Submission

### ISSUE THREAD

**Issue by hhwer** [Alue-Benchmark/alue_baselines#8] opened 2023-08-27 09:43 UTC
Hello, I am unable to submit the results right now. At the very beginning, due to my file naming problem, the system gave me a prompt when submitting, and I made corresponding changes. Now, the submission is still not successful, and the system just displays " ×Submission" without any prompt.

**Comment by hseelawi** [comment] 2023-08-27 11:53
Hello @hhwer and thanks for your interest in `ALUE`. I had a quick look, and it seems like the issue is mainly stemming from your `v_reg.tsv` submission file. Would you please ensure it has the correct data types, and conforms to the expected format? You can find this [notebook ](https://github.com/Alue-Benchmark/alue_baselines/blob/master/notebooks/USE/V-reg.ipynb) that we used to prepare our `v_reg.tsv` submission for the `USE` model.

Generally speaking, this [directory ](https://github.com/Alue-Benchmark/alue_baselines/tree/master/notebooks/USE) contains all the notebooks we developed to create our `USE` baseline submission, and should be consulted for the expected format for each submission file, and their expected names.

For the `MADAR` dataset please use the data provided [here](https://groups.google.com/g/aluebenchmark/c/cuOE18cjegQ/m/DmZ2gff8AwAJ).

If you face anymore issues, please let us know.

Best of luck with your submission.

**Comment by hhwer** [comment] 2023-08-29 05:41
Thanks

**Comment by hseelawi** [comment] 2023-08-31 08:53
I am going to close this issue now. If you face anything else, please let us know.

**Closed as completed by hseelawi** 2023-08-31 08:53 UTC

**Comment by HaniItani** [comment] 2024-06-11 11:50
Hello @hseelawi,

Can you please forward the correct train/dev/test split of MDD to my email hani.itani.2@kaust.edu.sa. I would like to make a submission to the leaderboard soon. Thank you very much in advance.

Best regards,
Hani

**Comment by hseelawi** [comment] 2024-06-11 12:01
Hello @HaniItani you should have them in your inbox now. Best of luck with your submission.
